server:
  port: 8080

dynamic-datasource:
    druid:
        #druid相关配置
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    read:
        url: jdbc:mysql://rm-2zehpfv6kh86c4l52o.mysql.rds.aliyuncs.com:3306/qifubao_dev
        username: afb_mysql
        password: J9DlVvbIeSAX
    write:
        url: jdbc:mysql://rm-2zehpfv6kh86c4l52o.mysql.rds.aliyuncs.com:3306/qifubao_test
        username: afb_mysql
        password: J9DlVvbIeSAX

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.dynamic.source.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql